HansKristian-Work/dxil-spirv

meson.build

Add a Meson build script

---

cfg_structurizer.cpp
cfg_structurizer.hpp
reference/shaders/control-flow/branch-return-2.comp
reference/shaders/control-flow/branch-return.comp
reference/shaders/control-flow/conditional-break-into-if-else-if-ladder-2.comp
reference/shaders/control-flow/conditional-break-into-if-else-if-ladder.comp
reference/shaders/control-flow/loop-continue-2.comp
reference/shaders/control-flow/loop-continue-3.comp
reference/shaders/control-flow/loop-continue.comp
shaders/control-flow/conditional-break-into-if-else-if-ladder-2.comp
shaders/control-flow/conditional-break-into-if-else-if-ladder.comp

Fixes some additional issues with Death Stranding shaders.

More CFG fixes

---

opcodes/dxil/dxil_waveops.cpp
reference/shaders/dxil-builtin/quad-read-at.comp
reference/shaders/dxil-builtin/quad-swap.comp
reference/shaders/dxil-builtin/wave-read-lane-at-optimizations.comp
shaders/dxil-builtin/wave-read-lane-at-optimizations.comp

Several games trigger this for some odd reason ...

Optimize WaveReadAtLane to quadBroadcast when possible

---

opcodes/dxil/dxil_sampling.cpp

Fixes blocky shadows in Horizon Zero Dawn
It only needs it on GatherCmp but I decided to do them all anyway, may as well.
This wasn't caught initially as the only one that doesn't error out with non-constant previously is gather.

Implement non-constant texture texel offsets

---

bc/module.cpp
dxil_converter.cpp
opcodes/converter_impl.hpp
opcodes/opcodes_llvm_builtins.cpp
opcodes/opcodes_llvm_builtins.hpp

Implement ConstantExpr casts

---

cfg_structurizer.cpp
reference/shaders/control-flow/branch-return-2.comp
reference/shaders/control-flow/branch-return.comp
reference/shaders/control-flow/branch.comp
reference/shaders/control-flow/loop-return.comp

It might be the case that one path is a break, while the other path
wants to merge with outer selection, but we can't since we don't have an
interim block. Attempts to fix this up.

Handle some cases with weird selection branches.

---

cfg_structurizer.cpp
dxil_converter.cpp
node.cpp
node.hpp
opcodes/dxil/dxil_sampling.cpp

More CFG fixes.

---

opcodes/dxil/dxil_ray_tracing.cpp
opcodes/dxil/dxil_ray_tracing.hpp
opcodes/opcodes_dxil_builtins.cpp
reference/shaders/dxil-builtin/ray-query.comp
shaders/dxil-builtin/ray-query.comp
test_shaders.py
third_party/glslang-spirv/SpvBuilder.cpp
third_party/glslang-spirv/SpvBuilder.h

Main missing thing is variable pointer to ray query object, but implementable since it's all based around indices anyways in the DXIL.

Implement RayQuery

---

dxil_converter.cpp
opcodes/converter_impl.hpp
opcodes/dxil/dxil_buffer.cpp
opcodes/dxil/dxil_sampling.cpp
opcodes/opcodes_dxil_builtins.cpp
reference/shaders/resources/typed-resources-16bit-sparse.frag
reference/shaders/resources/typed-resources-16bit.bindless.frag
reference/shaders/resources/typed-resources-16bit.frag
shaders/resources/typed-resources-16bit-sparse.frag
shaders/resources/typed-resources-16bit.bindless.frag
shaders/resources/typed-resources-16bit.frag

Need to cast back and forth since Vulkan only allows 32-bit here.
Fixes FidelityFX FSR 16-bit shaders in new RE: Village update.

Handle 16-bit typed resources.

---

opcodes/dxil/dxil_geometry.cpp
opcodes/dxil/dxil_geometry.hpp
opcodes/opcodes_dxil_builtins.cpp
reference/shaders/semantics/view-id.frag
reference/shaders/semantics/view-id.vert
shaders/semantics/view-id.frag
shaders/semantics/view-id.vert
spirv_module.cpp

Trivially maps to BuiltInViewIndex.

Add SV_ViewID support.

---

opcodes/dxil/dxil_arithmetic.cpp
opcodes/dxil/dxil_arithmetic.hpp
opcodes/opcodes_dxil_builtins.cpp
reference/shaders/dxil-builtin/sm64-packed-arithmetic.ssbo.comp
shaders/dxil-builtin/sm64-packed-arithmetic.ssbo.comp

Not ideal, but a compiler could figure it out.

Implement SM 6.4 packed arithmetic intrinsics.

---

cfg_structurizer.cpp
cfg_structurizer.hpp

Use improved escape analysis to eliminate dead blocks.

Tighten up implementation of control_flow_is_escaping().

---

bc/instruction.cpp
bc/module.cpp
bc/type.cpp
bc/type.hpp
cfg_structurizer.cpp
cfg_structurizer.hpp
dxil_converter.cpp
spirv_module.cpp
spirv_module.hpp

Fixes some insane control flow in Halo Infinite.

Interlocked merge scope fix

---

cfg_structurizer.cpp
reference/shaders/control-flow/loop-continue-2.comp
reference/shaders/control-flow/loop-continue.comp

This makes no progress and only erases a legitimate input.

CFG: Do not attempt checking a frontier == incoming block.

---

cfg_structurizer.cpp
cfg_structurizer.hpp
node.cpp
node.hpp

Need to land a set of changes before getting through the rest of Nanite fixes. First, land various changes which don't affect repro suite all that much.

Various CFG fixes to prepare for further Nanite fixes

---

cfg_structurizer.cpp
dxil_converter.cpp
ir.hpp
node.cpp
spirv_module.cpp

We only checked cases, but default block is also block like any other.
Refactor default blocks to be just a normal case label.

Consider impossible fallthrough scenarios with default blocks as well.

---

cfg_structurizer.cpp
node.cpp
node.hpp

Need to do a complete backtrace, not just single pred analysis.

Rewrite check for post_dominates_any_work() to work with ladder merges.

---

cfg_structurizer.cpp
cfg_structurizer.hpp
dxil_converter.cpp
node.cpp
node.hpp
spirv_module.cpp

Fix degenerate PHI scenarios and handle double infinite loops

---

meson.build
third_party/bc-decoder/llvm_bitreader.h
third_party/bc-decoder/llvm_decoder.cpp

Fixes some associated warnings.

meson: Set b_ndebug=if-release.

---

cfg_structurizer.cpp
cfg_structurizer.hpp
reference/shaders/control-flow/loop-inside-infinite-loop-2.frag
reference/shaders/control-flow/loop-inside-infinite-loop.frag
shaders/control-flow/loop-inside-infinite-loop-2.frag
shaders/control-flow/loop-inside-infinite-loop.frag

Found more interesting cases with infinite loops and nested loops inside them.

Various CFG fixes

---

cfg_structurizer.cpp
cfg_structurizer.hpp

Hit case in Capcom Arcade 2nd Stadium.

Handle more scenarios where natural merge != merge in switch blocks.

---

opcodes/opcodes_llvm_builtins.cpp

It is apparently legal to bitcast a pointer-to-array into pointer to
scalar while changing the pointer type ...
Refactor the value remapping to handle layered constant expressions
better.

Handle more complex constant expressions.

---

cfg_structurizer.cpp

Fixes a bug in Halo Infinite when firing the Skewer gun.

Avoid catastrophic cancellation of PHI nodes when merging PHI nodes.

---

cfg_structurizer.cpp

Need to consider that inner continue blocks without normal succ is not considered an exit.
Fix #134.

Fix bug in find_common_post_dominator_with_ignored_break.

---

node.cpp

Fixes benign assert in our test suite.

Don't add fake_succ if we already have a normal succ.

---

opcodes/dxil/dxil_pixel_ops.cpp
reference/shaders/dxil-builtin/derivative.sm60.frag
reference/shaders/dxil-builtin/derivative.sm60.native-fp16.frag
shaders/dxil-builtin/derivative.sm60.frag
shaders/dxil-builtin/derivative.sm60.native-fp16.frag

Only allow FP32 derivatives.

---

opcodes/dxil/dxil_arithmetic.cpp
opcodes/dxil/dxil_arithmetic.hpp
opcodes/opcodes_dxil_builtins.cpp

Needed for FSR3 frame generation.

Implement MSAD instruction.

---

opcodes/converter_impl.hpp
opcodes/dxil/dxil_mesh.cpp
reference/shaders/stages/mesh-basic-line.mesh
reference/shaders/stages/mesh-basic.mesh
reference/shaders/stages/mesh-clip-cull.mesh
spirv_module.cpp
third_party/glslang-spirv/spvIR.h

Intended to work around mesh shader compiler bugs on NV.
@doitsujin found the potential WAR candidate.

Mesh shader early return workaround

---

dxil_parser.cpp
memory_stream.cpp
memory_stream.hpp

The blob size is incorrectly calculated

Fix Failed to parse dxil, which was converted from dxbc
