HansKristian-Work/dxil-spirv

meson.build
Fixes compilation under MSVC on Windows.
=> Define NOMINMAX on Meson builds

meson.build
=> build: Drop minimum meson version

scratch_pool.hpp
Fixes error with `meson ... --unity=on ...` build.
=> Fix missing header guard

cfg_structurizer.cpp, cfg_structurizer.hpp, opcodes/dxil/dxil_arithmetic.cpp, opcodes/dxil/dxil_resources.cpp, reference/shaders/control-flow/dual-inner-loop-early-return.comp, reference/shaders/control-flow/loop-break-2.comp, reference/shaders/control-flow/loop-break.comp, reference/shaders/control-flow/loop-return.comp, reference/shaders/control-flow/nested-loop-break-2.comp, reference/shaders/control-flow/nested-loop-break.comp, util/thread_local_allocator.hpp
Rewriting the CFG can cause dominance relationships to break. Lower SSA variables to OpVariable instead when this edge case occurs.
=> Fixup SSA variables which have their dominance broken

opcodes/dxil/dxil_waveops.cpp, reference/shaders/dxil-builtin/wave-active-ballot-discard.demote-to-helper.frag, reference/shaders/dxil-builtin/wave-active-ballot-discard.frag, reference/shaders/dxil-builtin/wave-active-ballot.demote-to-helper.frag, reference/shaders/dxil-builtin/wave-active-ballot.frag, shaders/dxil-builtin/wave-active-ballot-discard.demote-to-helper.frag, shaders/dxil-builtin/wave-active-ballot-discard.frag, shaders/dxil-builtin/wave-active-ballot.demote-to-helper.frag, shaders/dxil-builtin/wave-active-ballot.frag, spirv_module.cpp
Some shaders seem to expect that helper lanes are explicitly masked out,
so do just that.
=> Mask out helper lanes in ballots.

bc/module.cpp
Sample of the code causing the issue.
```
; <label>:344                                     ; preds = %356
%345 = shl nsw i32 %373, 3
%346 = and i32 %345, 24
%347 = lshr i32 %211, %346
%348 = and i32 %347, 255
%349 = uitofp i32 %348 to float
%350 = fmul fast float %349, 0x3F70101020000000
%351 = fmul fast float %350, %350
%352 = fmul fast float %351, %316
%353 = getelementptr inbounds [4 x float], [4 x float]* %14, i32 0, i32 %373
%354 = load float, float* %353, align 4, !tbaa !26
%355 = fmul fast float %354, %316
br label %389
```
Line %353 refers to %373 which is a forward reference at this point. The get_value code just simply prints an error whereas other instructions properly using the following op as the type.
=> Fix for when GEP refers to a forward reference for the third operand.

node.cpp, node.hpp
The graph traversal of dominates_all_reachable_exits was hitting the same nodes repeatedly and was seemingly in an infinite loop but was instead just taking an incredibly long time to finish. This was due to checking the same nodes each time they were encountered instead of just recording they have been checked.
[e5010e4ebf22196d.zip](https://github.com/HansKristian-Work/dxil-spirv/files/6361639/e5010e4ebf22196d.zip)
=> Shader seemingly hits infinite loop in graph traversal but instead just takes incredibly long to complete.

bc/module.cpp, bc/type.hpp, bc/value.cpp, dxil_converter.cpp, opcodes/opcodes_llvm_builtins.cpp, opcodes/opcodes_llvm_builtins.hpp, reference/shaders/llvm-builtin/glitched-integer-width.comp, shaders/llvm-builtin/glitched-integer-width.comp
LLVM IR supports "weird" integer sizes, and it implies that backend
deals with masking where appropriate.
In contexts where sign matters, we need to extend the input to physical
bitwidth from logical bitwidth.
For now, this is probably not exhaustive, but handle trunc/zext/sext and
some arithmetic opcodes which are sign sensitive.
Obsoletes #41.
=> Handle "odd" integer sizes.

bc/module.cpp
Fixes parsing my constexpr test shader.
No idea how we didn't run into this on RE8's shaders.
=> Use constant type for CE_CAST

dxil_converter.cpp, opcodes/converter_impl.hpp, opcodes/dxil/dxil_ray_tracing.cpp, opcodes/opcodes_dxil_builtins.cpp
In DXIL, you can use the same _alloca for these, so we need to allocate a temporary and copy in the instances where this happens.
Otherwise, just treat the alloca like a RayPayload as normal.
Prerequisite of #52
=> Implement temp storage copies for RayPayloads and CallableData

checkout_dxc.sh, reference/shaders/control-flow/dual-inner-loop-early-return.comp, reference/shaders/dxil-builtin/call-shader.rgen, reference/shaders/dxil-builtin/clip.demote-to-helper.frag, reference/shaders/dxil-builtin/clip.frag, reference/shaders/dxil-builtin/discard.demote-to-helper.frag, reference/shaders/dxil-builtin/discard.frag, reference/shaders/dxil-builtin/wave-active-ballot-discard.demote-to-helper.frag, reference/shaders/dxil-builtin/wave-active-ballot-discard.frag, reference/shaders/llvm-builtin/glitched-integer-width.comp, reference/shaders/resources/acceleration-structure.bindless.rgen, reference/shaders/resources/acceleration-structure.bindless.ssbo-rtas.local-root-signature.rgen, reference/shaders/resources/acceleration-structure.local-root-signature.root-descriptor.rgen, reference/shaders/resources/cbv-array-nonuniform.frag, reference/shaders/resources/cbv.bindless.root-constant.cbv-as-ssbo.frag, reference/shaders/resources/cbv.bindless.root-constant.frag, reference/shaders/resources/rt-resources.bindless.local-root-signature.rmiss, reference/shaders/semantics/inner-coverage.noglsl.frag, reference/shaders/stages/callable-chain.rcall, reference/shaders/stages/raygen-complex-storage-class.rgen, reference/shaders/stages/raygen.rgen, reference/shaders/stages/raymiss-chain.rmiss, shaders/dxil-builtin/wave-reduce.comp, shaders/semantics/position-short.frag, shaders/semantics/position-short.vert
Need this for constexpr cast shaders.
Marked as draft as `raygen-complex-storage-class.rgen` currently fails with `A memory declaration object must be used in TraceRayKHR.` when being reflected back.
=> Update DXC for Test Suite

reference/shaders/dxil-builtin/texture-gather-4offset.frag, shaders/dxil-builtin/texture-gather-4offset.frag
DXC ends up producing 4 texture gathers here, and these are called out as being potentially variable in the HLSL spec.
In the const case, we could fold this to ConstOffsets in the future but it might be better to let the driver do that as it's a pretty easy pattern.
=> Add test for Gather with 4 offsets

bc/instruction.cpp, bc/instruction.hpp, bc/module.cpp, opcodes/dxil/dxil_arithmetic.cpp, opcodes/opcodes_llvm_builtins.cpp, reference/shaders/dxil-builtin/fmad-precise.frag, reference/shaders/llvm-builtin/precise_math.frag, shaders/llvm-builtin/precise_math.frag
- Correctly split expressions for precise mad.
- NoContraction on fma() is meaningless as SPIR-V fma is invariant.
- Check precision sensitivity of builtin arithmetic instructions.
- Parse fast math flags.
=> Handle precision qualifiers better.

cfg_structurizer.cpp, cfg_structurizer.hpp, reference/shaders/control-flow/loop-return.comp
Fixes undef being used as Phi inputs. Fixes weird sun particles punching through walls in RE8.
Also optimizes PHI placement a fair bit and avoids generating useless PHI frontiers.
=> More CFG fixes

cfg_structurizer.cpp
We have to backtrace inner loop bodies as well since they may not be
reachable in the reversed CFG. If a loop header can backtrace to header,
any block reaching the loop header's continue block also has this
property.
Fixes some potential infinite loops when updating immediate post
dominators.
Fix #65.
Supersedes #66.
=> Fix LoopBacktracer::trace_to_parent.

dxil.hpp, dxil_parser.cpp, dxil_parser.hpp
Esoteric feature. Defer implementation of this until we need to.
=> Parse enough of SM 6.4 library subobject metadata to report failures.

dxil_converter.cpp, opcodes/converter_impl.hpp, opcodes/dxil/dxil_arithmetic.cpp, opcodes/dxil/dxil_buffer.cpp, opcodes/dxil/dxil_compute.cpp, opcodes/dxil/dxil_ray_tracing.cpp, opcodes/dxil/dxil_resources.cpp, opcodes/dxil/dxil_sampling.cpp, opcodes/opcodes_llvm_builtins.cpp
If PHI inputs consumed the values first, they will be stale. Go through
a common code path so we handle all scenarios where IDs are rewritten.
=> Never rewrite IDs in value_map directly.

node.cpp, node.hpp, node_pool.cpp
Detect this scenario and create intermediate blocks instead.
Fix #78.
=> Don't create duplicate edges when rewriting branches.

cfg_structurizer.cpp, cfg_structurizer.hpp
If a break merge has actual operations associated with it, we must
duplicate the block and duplicate all the opcodes.
=> Handle impossible break merge scenarios.

cfg_structurizer.cpp, cfg_structurizer.hpp
If there are unordered fallthroughs, we need to rethink the switch and
emit a loop for the outer merge and merge the switch to the target of
unordered fallthroughs instead.
=> Handle impossible case fallthrough cases.

opcodes/converter_impl.hpp, opcodes/dxil/dxil_arithmetic.cpp, opcodes/opcodes_dxil_builtins.cpp
HZD shows invariance issues if we don't consider this case since we have
observed pack -> imageStore -> unpack patterns in the wild, and at least
NV compiler appears to optimize away pack/unpack, leaving full FP32
precision in one shaders and FP16 precision in another, leading to
invariance issues, despite shader being declared as invariant.
OpQuantizeF16 seems to be the only workaround.
=> Honor dx.precise on unpack/pack FP instructions.

cfg_structurizer.cpp, cfg_structurizer.hpp, node.cpp
It is possible that a loop breaks out a few levels while the continuing
path after the loop breaks out of more levels.
This is impossible to represent normally.
We have to transpose the loop such that the breaking construct is the
merge point, and the continuing path becomes the breaking construct
instead.
This obliterates the CFG after retargeting branches like this, so we
have to recompute the CFG before doing anything else.
Ridiculously complicated ... :(
=> Handle transposed loops.

cfg_structurizer.cpp, cfg_structurizer.hpp, reference/shaders/control-flow/interleaved-unrolled-loop-breaks.comp, shaders/control-flow/interleaved-unrolled-loop-breaks.comp
In heavily unrolled loops with many different breaks, we can end up with
code that is impossible to express with normal structured control flow
without deinterleaving the breaks.
The strategy is to pull all break blocks to a merge block which
switch-dispatches to the appropriate break construct, then reconvenes at
the merge block.
=> Serialize interleaved merge scopes.

dxil_converter.cpp, opcodes/converter_impl.hpp, opcodes/dxil/dxil_buffer.cpp, opcodes/dxil/dxil_common.cpp, opcodes/dxil/dxil_common.hpp, opcodes/dxil/dxil_resources.cpp, opcodes/dxil/dxil_sampling.cpp, opcodes/opcodes_llvm_builtins.cpp, opcodes/opcodes_llvm_builtins.hpp
If our pretend-vectors are used in contexts that aren't directly compatible we have to explode the vectors into structs instead to accurately observe the type system in DXIL.
=> Handle scenario where struct is used as PHI instead of vector.

dxil_converter.cpp, opcodes/converter_impl.hpp, opcodes/dxil/dxil_waveops.cpp, opcodes/opcodes_llvm_builtins.cpp, opcodes/opcodes_llvm_builtins.hpp, reference/shaders/dxil-builtin/wave-all-equal.frag
In waterfall loops, some games rely on helper lanes to participate.
Detect WaveReadFirstLane(x) == x patterns and act accordingly if that boolean is used as part of a branch instruction.
=> Implement workaround for WaveReadFirstLane in control flow.

node.cpp
Fixes some Callisto Protocol ray tracing shaders being translated to invalid SPIR-V.
=> Allow loops in dominates_all_reachable_exits

dxil_converter.cpp
Trivial, but improves the debugging experience for things like Flight Simulator 2020.
=> Log register space and index when resource remapping fails.

opcodes/dxil/dxil_sampling.cpp
The compare flag is omitted when build sampled image.
=> Fix handling of dx.op.textureGatherCmp

reference/shaders/ags/cs_wmma_copy_transpose_fp16.sm66.ssbo.comp, reference/shaders/ags/cs_wmma_f32_16x16x16_f16_quant_fp8.sm66.ssbo.comp, spirv_module.cpp
Help the compiler out by emitting vec2 16bit instructions, nir_opt_vectorize can't deal with this. Also avoid 8bit math, that's also only causing pain.
=> vectorize emulated fp16 -> fp8 conversion

opcodes/dxil/dxil_nvapi.cpp, opcodes/dxil/dxil_nvapi.hpp, reference/shaders/nvapi/get-special-global-timer.nvapi.ssbo.rgen, shaders/nvapi/get-special-global-timer.nvapi.ssbo.rgen
Implemented on top of shader clock extension. Nothing huge but it lays some groundwork for future opcodes.
Right now it appears that we don't need to persist any kind of `bool was_committed;` if we carefully check whether all inputs are already set.
=> Add support for NvGetSpecial(GLOBAL_TIMER).

opcodes/dxil/dxil_nvapi.cpp, third_party/glslang-spirv/SpvBuilder.cpp, third_party/glslang-spirv/SpvBuilder.h
Enough to create simple hit objects and extract most scalars out of them.
The bitcast/conversion dance around floats and bools is slightly annoying but unfortunately I don't have any ideas about improving it.
Notably, I'm not assigning to `handle_to_storage_class` when creating `HitObjectNV` variables (like for example `emit_allocate_ray_query` does), because at the point they are allocated, I don't have the instruction they will be rewritten with yet. Doesn't seem to be a problem in practice though…?
=> NvHitObject, part 1
